server:
  port: 6061
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus2?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 7
    # elasticsearch相关
    # elasticsearch:
    #   uris: http://localhost:9200
    #   username: elastic
    #   password: your_password
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 项目目录
project:
  folder: D:/vibe-coding/smart-campus
resource:
  temp-dir: resource/temp
  file-dir: resource/files
  upload-session-ttl-minutes: 120
# 日志级别
log:
  root:
    level: debug
